# Generated by Django 5.0.6 on 2024-07-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='company_name',
            new_name='signatory',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='company_contact_no',
        ),
        migrations.AddField(
            model_name='preference',
            name='Logo',
            field=models.ImageField(default=1, upload_to='logo/'),
            preserve_default=False,
        ),
    ]
