# Generated by Django 5.0.6 on 2024-07-14 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_position_rename_company_name_preference_signatory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.position'),
            preserve_default=False,
        ),
    ]
