# Generated by Django 5.0.6 on 2024-07-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_member_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('signatory', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='signatory',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='Logo',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='preference',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
