# Generated by Django 5.0.6 on 2024-07-14 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_branch_rename_signatory_preference_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preference',
            name='company_name',
            field=models.CharField(default='Company Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='preference',
            name='description',
            field=models.CharField(default='Description', max_length=255),
        ),
        migrations.AlterField(
            model_name='preference',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
