# Generated by Django 5.0.6 on 2024-07-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_member_branch_alter_preference_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='pm_in_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
