# Generated by Django 5.0.6 on 2024-07-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_shift_pm_in_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='day_off',
        ),
    ]
