# Generated by Django 5.0.6 on 2024-07-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_member_day_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='period_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Dual', 'Dual')], default='Dual', max_length=20),
        ),
    ]
